import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {ThemeProvider} from "@/components/theme-provider";

import "./globals.css";
import {ModeToggle} from "@/components/ui/toggle-mode";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* attribute="class" - means theme will be toggled via classes */}
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
      >
        <nav className="flex justify-between">
            <h1>Recipes</h1>
            <ModeToggle />
        </nav>
        {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
